// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteProspeccaoClientes.Data.Models;

namespace TesteProspeccaoClientes.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180905224402_ProspeccaoClienteMigration")]
    partial class ProspeccaoClienteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("TesteProspeccaoClientes.Data.Models.ClienteModel", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConteudoConversa");

                    b.Property<DateTime>("DataHoraConversa");

                    b.Property<string>("Email");

                    b.Property<string>("NomeContato");

                    b.Property<string>("NomeEmpresa");

                    b.Property<string>("Telefone");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TesteProspeccaoClientes.Data.Models.ClienteServicoModel", b =>
                {
                    b.Property<int>("ClienteId");

                    b.Property<int>("ServicoId");

                    b.HasKey("ClienteId", "ServicoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ClientesServicos");
                });

            modelBuilder.Entity("TesteProspeccaoClientes.Data.Models.ServicoModel", b =>
                {
                    b.Property<int>("ServicoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeServico");

                    b.HasKey("ServicoId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("TesteProspeccaoClientes.Data.Models.ClienteServicoModel", b =>
                {
                    b.HasOne("TesteProspeccaoClientes.Data.Models.ClienteModel", "Cliente")
                        .WithMany("ClienteServico")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TesteProspeccaoClientes.Data.Models.ServicoModel", "Servico")
                        .WithMany("ClienteServico")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
