// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTria.Models;

namespace TesteTria.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("TesteTria.Models.ClienteModel", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConteudoConversa");

                    b.Property<DateTime>("DataHoraConversa");

                    b.Property<string>("Email");

                    b.Property<string>("NomeContato");

                    b.Property<string>("NomeEmpresa");

                    b.Property<int?>("ServicoId");

                    b.Property<string>("Telefone");

                    b.HasKey("ClienteId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TesteTria.Models.ServicoModel", b =>
                {
                    b.Property<int>("ServicoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeServico");

                    b.HasKey("ServicoId");

                    b.ToTable("ServicoModel");
                });

            modelBuilder.Entity("TesteTria.Models.ClienteModel", b =>
                {
                    b.HasOne("TesteTria.Models.ServicoModel", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId");
                });
#pragma warning restore 612, 618
        }
    }
}
